const wordList = ['ABBEY','ABBOT','ABIDE','ABODE','ABORT','ABOUT','ABOVE','ABUSE','ABYSS','ACHES','ACIDS','ACORN','ACRES','ACTED','ACTOR','ACUTE','ADAPT','ADDED','ADEPT','ADMIN','ADMIT','ADOBE','ADOPT','ADORE','ADORN','ADULT','AEGIS','AFTER','AGAIN','AGENT','AGILE','AGING','AGONY','AGREE','AHEAD','AIDED','AIDES','AIMED','AIRED','AISLE','ALARM','ALBUM','ALERT','ALGAE','ALIAS','ALIBI','ALIEN','ALIGN','ALIKE','ALIVE','ALLEY','ALLOW','ALLOY','ALOFT','ALONE','ALONG','ALOUD','ALPHA','ALTAR','ALTER','AMAZE','AMBER','AMEND','AMONG','AMPLE','AMUSE','ANGEL','ANGER','ANGLE','ANGRY','ANGST','ANIME','ANKLE','ANNEX','ANNOY','ANVIL','APART','APPLE','APPLY','APRON','APTLY','ARBOR','AREAS','ARENA','ARGUE','ARISE','ARMED','ARMOR','AROMA','AROSE','ARRAY','ARROW','ARSON','ASHES','ASIDE','ASKED','ASPEN','ASSET','ATLAS','ATOMS','ATTIC','AUDIO','AUDIT','AUNTS','AVERT','AVIAN','AVOID','AWAIT','AWAKE','AWARD','AWARE','AWFUL','AZURE','BACKS','BACON','BADGE','BADLY','BAGEL','BAGGY','BAKED','BAKER','BANDS','BANGS','BANJO','BANKS','BARGE','BARKS','BARNS','BARON','BASAL','BASED','BASES','BASIC','BASIL','BASIN','BASIS','BATCH','BATHE','BATHS','BATON','BAYOU','BEACH','BEADS','BEAMS','BEANS','BEARD','BEARS','BEAST','BEATS','BEECH','BEETS','BEGAN','BEGIN','BEGUN','BEIGE','BEING','BELLE','BELLS','BELLY','BELOW','BELTS','BENCH','BENDS','BERRY','BERTH','BESET','BIBLE','BIGOT','BIKER','BIKES','BILLS','BINDS','BINGE','BINGO','BIRCH','BIRDS','BIRTH','BISON','BITES','BLACK','BLADE','BLAME','BLAND','BLANK','BLAST','BLAZE','BLEAK','BLEED','BLEND','BLESS','BLIND','BLING','BLINK','BLISS','BLITZ','BLOCK','BLOGS','BLOKE','BLOND','BLOOD','BLOOM','BLOWN','BLOWS','BLUES','BLUFF','BLUNT','BLUSH','BOARD','BOAST','BOATS','BOGUS','BOILS','BOLTS','BOMBS','BONDS','BONES','BONUS','BOOED','BOOKS','BOOST','BOOTH','BOOTS','BOOZE','BORED','BOUND','BOUTS','BOWED','BOWLS','BOXED','BOXER','BOXES','BRACE','BRAID','BRAIN','BRAKE','BRAND','BRASS','BRAVE','BRAVO','BRAWL','BREAD','BREAK','BREED','BRIBE','BRICK','BRIDE','BRIEF','BRINE','BRING','BRINK','BRISK','BROAD','BROKE','BROOD','BROOK','BROOM','BROTH','BROWN','BROWS','BRUNT','BRUSH','BRUTE','BUCKS','BUDGE','BUFFS','BUGGY','BUILD','BUILT','BULBS','BULGE','BULKY','BULLS','BULLY','BUMPS','BUMPY','BUNCH','BUNNY','BURNS','BURNT','BURST','BUSES','BUSTS','BUTCH','BUTTE','BUYER','BYTES','CABAL','CABIN','CABLE','CACHE','CADET','CAFES','CAGED','CAGES','CAKES','CALLS','CAMEL','CAMEO','CAMPS','CANAL','CANDY','CANES','CANOE','CANON','CARAT','CARBS','CARDS','CARED','CARES','CARGO','CAROL','CARRY','CARTS','CARVE','CASES','CASTE','CASTS','CATCH','CATER','CAUSE','CAVES','CEASE','CEDAR','CEDED','CELLO','CELLS','CENTS','CHAIN','CHAIR','CHALK','CHAMP','CHANT','CHAOS','CHAPS','CHARM','CHART','CHASE','CHATS','CHEAP','CHEAT','CHECK','CHEEK','CHEER','CHEFS','CHEMO','CHESS','CHEST','CHIEF','CHILD','CHILI','CHILL','CHIME','CHIPS','CHOIR','CHOKE','CHOPS','CHORD','CHORE','CHOSE','CHUCK','CHUNK','CHURN','CHUTE','CIDER','CIGAR','CIRCA','CITED','CITES','CIVIC','CIVIL','CLAIM','CLAMP','CLAMS','CLANS','CLASH','CLASP','CLASS','CLAWS','CLEAN','CLEAR','CLERK','CLICK','CLIFF','CLIMB','CLIPS','CLOAK','CLOCK','CLONE','CLOSE','CLOTH','CLOUD','CLOUT','CLOWN','CLUBS','CLUES','COACH','COAST','COATS','COBRA','COCOA','CODED','CODES','CODEX','COILS','COINS','COLOR','COLTS','COMBO','COMBS','COMES','COMET','COMFY','COMIC','COMMA','CONDO','CONES','COOKS','COOLS','CORAL','CORDS','CORES','CORNY','CORPS','COSTS','COUCH','COUGH','COULD','COUNT','COURT','COVER','CRABS','CRACK','CRAFT','CRAMP','CRANE','CRANK','CRASH','CRATE','CRAVE','CRAWL','CRAZE','CRAZY','CREAM','CREED','CREEK','CREEP','CREPT','CREST','CREWS','CRIED','CRIES','CRIME','CRISP','CROCK','CROOK','CROPS','CROSS','CROWD','CROWN','CROWS','CRUDE','CRUEL','CRUSH','CRUST','CRYPT','CUBES','CUBIC','CUFFS','CULTS','CURED','CURES','CURLS','CURLY','CURRY','CURSE','CURVE','CURVY','CYBER','CYCLE','DAILY','DAIRY','DAISY','DANCE','DANDY','DARED','DARES','DARTS','DATED','DATES','DAZED','DEALS','DEALT','DEATH','DEBIT','DEBTS','DEBUT','DECAL','DECAY','DECKS','DECOR','DECOY','DEEDS','DEEMS','DEFER','DEITY','DELAY','DELTA','DELVE','DEMON','DENIM','DENSE','DEPOT','DEPTH','DERBY','DESKS','DETER','DETOX','DEVIL','DIARY','DICED','DIETS','DIGIT','DINER','DIRTY','DISCO','DISCS','DISKS','DITCH','DIVAS','DIVER','DIVES','DIZZY','DOCKS','DODGE','DODGY','DOGMA','DOING','DOLLS','DONOR','DOORS','DOSES','DOUBT','DOUGH','DOVES','DOWNS','DOWRY','DOZEN','DRAFT','DRAGS','DRAIN','DRAKE','DRAMA','DRANK','DRAWN','DRAWS','DREAD','DREAM','DRESS','DRIED','DRIER','DRIES','DRIFT','DRILL','DRINK','DRIVE','DROID','DRONE','DROOL','DROPS','DROVE','DROWN','DRUGS','DRUMS','DRUNK','DRYER','DUCKS','DUCTS','DUKES','DUNES','DUPED','DUSTY','DWELL','DYING','EAGER','EAGLE','EARLY','EARNS','EARTH','EASED','EATEN','EATER','EBONY','EDGED','EDGES','EDICT','EDITS','EERIE','EIGHT','ELBOW','ELDER','ELECT','ELITE','ELVES','EMAIL','EMITS','EMPTY','ENACT','ENDED','ENEMY','ENJOY','ENTER','ENTRY','ENVOY','EPOCH','EPOXY','EQUAL','EQUIP','ERASE','ERODE','ERROR','ESSAY','ETHER','ETHIC','EVADE','EVENT','EVERY','EVILS','EVOKE','EXACT','EXAMS','EXCEL','EXECS','EXERT','EXILE','EXIST','EXITS','EXPEL','EXTRA','FABLE','FACED','FACES','FACET','FACTS','FADED','FADES','FAILS','FAINT','FAIRY','FAITH','FAKED','FAKES','FALLS','FALSE','FAMED','FANCY','FANGS','FARCE','FARED','FARES','FARMS','FATAL','FATED','FATES','FAULT','FAUNA','FAVOR','FEARS','FEAST','FEATS','FEEDS','FEELS','FELON','FENCE','FERAL','FERNS','FERRY','FETCH','FEVER','FEWER','FIBER','FIELD','FIEND','FIERY','FIFTH','FIFTY','FIGHT','FILED','FILES','FILLS','FILMS','FILTH','FINAL','FINDS','FINED','FINER','FINES','FIRED','FIRES','FIRMS','FIRST','FISHY','FISTS','FIVES','FIXED','FIXER','FIXES','FLAGS','FLAIR','FLAKE','FLAME','FLANK','FLAPS','FLARE','FLASH','FLASK','FLATS','FLAWS','FLEAS','FLEET','FLESH','FLICK','FLIES','FLING','FLINT','FLIPS','FLIRT','FLOAT','FLOCK','FLOOD','FLOOR','FLOPS','FLOSS','FLOUR','FLOWN','FLOWS','FLUFF','FLUID','FLUKE','FLUNG','FLUSH','FLUTE','FLYER','FOCAL','FOCUS','FOGGY','FOLDS','FOLIO','FOLKS','FOLLY','FONTS','FOODS','FOOLS','FORAY','FORCE','FORGE','FORKS','FORMS','FORTH','FORTS','FORTY','FORUM','FOULS','FOUND','FOURS','FOXES','FOYER','FRAIL','FRAME','FRAUD','FREED','FREES','FRESH','FRIAR','FRIED','FRIES','FROGS','FRONT','FROST','FROWN','FROZE','FRUIT','FUDGE','FUELS','FULLY','FUMES','FUNDS','FUNGI','FUNKY','FUNNY','FURRY','FUSED','FUSES','FUSSY','FUZZY','GABLE','GAINS','GAMER','GAMES','GAMMA','GANGS','GASES','GATED','GATES','GATOR','GAUGE','GEARS','GEEKS','GEESE','GENES','GENIE','GENRE','GENTS','GENUS','GERMS','GHOST','GIANT','GIDDY','GIFTS','GILLS','GIRLS','GIRLY','GIVEN','GIVER','GIVES','GLAND','GLARE','GLASS','GLAZE','GLIDE','GLOBE','GLOOM','GLORY','GLOSS','GLOVE','GLUED','GNOME','GOALS','GOATS','GODLY','GOING','GOODS','GOOFY','GOONS','GOOSE','GORGE','GOWNS','GRABS','GRACE','GRADE','GRAFT','GRAIN','GRAMS','GRAND','GRANT','GRAPE','GRAPH','GRASP','GRASS','GRATE','GRAVE','GRAVY','GRAZE','GREAT','GREED','GREEN','GREET','GRIDS','GRIEF','GRILL','GRIME','GRIND','GRIPS','GROAN','GROOM','GROSS','GROUP','GROVE','GROWL','GROWN','GROWS','GUARD','GUESS','GUEST','GUIDE','GUILD','GUILT','GUISE','GUSTS','HABIT','HACKS','HAILS','HAIRS','HAIRY','HALLS','HANDS','HANGS','HAPPY','HARDY','HARMS','HARSH','HASTE','HASTY','HATCH','HATED','HATER','HATES','HAUNT','HAVEN','HAVOC','HAWKS','HEADS','HEALS','HEAPS','HEARD','HEARS','HEART','HEATS','HEAVY','HEDGE','HEELS','HEFTY','HEIRS','HEIST','HELPS','HERBS','HERDS','HERON','HIDES','HIGHS','HIKES','HILLS','HINGE','HINTS','HIPPO','HIRED','HIRES','HITCH','HIVES','HOARD','HOBBY','HOIST','HOLDS','HOLED','HOLES','HOMES','HONED','HONEY','HONOR','HOODS','HOOKS','HOOPS','HOPED','HOPES','HORDE','HORNS','HORSE','HOSTS','HOTEL','HOUND','HOURS','HOUSE','HOVER','HUMAN','HUMID','HUMOR','HUNCH','HUNTS','HURRY','HURTS','HUTCH','HYPED','HYPER','ICING','ICONS','IDEAL','IDEAS','IDOLS','IMAGE','IMPLY','INBOX','INCUR','INDEX','INEPT','INERT','INFER','INKED','INLET','INNER','INPUT','INTEL','IONIC','IRONS','IRONY','ISLES','ISSUE','ITCHY','ITEMS','IVORY','JACKS','JAILS','JEANS','JELLY','JERKY','JEWEL','JOINS','JOINT','JOKED','JOKER','JOKES','JOLLY','JUDGE','JUICE','JUICY','JUMBO','JUMPS','KAPPA','KARMA','KAYAK','KEBAB','KEEPS','KHAKI','KICKS','KILOS','KINDS','KINGS','KNACK','KNEEL','KNEES','KNIFE','KNOBS','KNOCK','KNOTS','KNOWN','KNOWS','KOALA','LABEL','LABOR','LACED','LACES','LACEY','LACKS','LAKES','LAMBS','LAMPS','LANCE','LANDS','LANES','LAPSE','LARGE','LASER','LASTS','LATCH','LATER','LATTE','LAUGH','LAWNS','LAYER','LEACH','LEADS','LEAFY','LEAKS','LEAKY','LEANS','LEAPS','LEAPT','LEARN','LEASE','LEASH','LEAST','LEAVE','LEDGE','LEECH','LEGAL','LEMON','LENDS','LEVEL','LEVER','LIARS','LIFTS','LIGHT','LIKED','LIKES','LILAC','LIMBS','LIMIT','LINED','LINEN','LINER','LINES','LINKS','LIONS','LISTS','LITER','LIVED','LIVES','LOADS','LOANS','LOBBY','LOCAL','LOCKS','LODGE','LOFTY','LOGIC','LONER','LONGS','LOOKS','LOOMS','LOOPS','LOOSE','LOSES','LOTUS','LOVED','LOVES','LOWER','LOWLY','LOYAL','LUCID','LUCKY','LUMPS','LUNAR','LUNCH','LUNGS','LURED','LYING','LYRIC','MACRO','MADAM','MADLY','MAFIA','MAGIC','MAGMA','MAIDS','MAILS','MAIZE','MAJOR','MAKER','MAKES','MALES','MALLS','MANGA','MANGO','MANIA','MANIC','MANLY','MANOR','MAPLE','MARCH','MARKS','MARRY','MARSH','MASKS','MASON','MATCH','MATES','MATTE','MAYBE','MAYOR','MEALS','MEANS','MEANT','MEATS','MEATY','MEDAL','MEDIA','MEDIC','MEETS','MELEE','MELON','MELTS','MEMES','MENUS','MERCH','MERCY','MERGE','MERIT','MERRY','MESSY','METAL','METER','METRO','MICRO','MIDST','MIGHT','MILES','MILKY','MILLS','MIMIC','MINCE','MINDS','MINED','MINER','MINES','MINOR','MINTS','MINUS','MISTY','MITES','MIXED','MIXER','MIXES','MOCKS','MODEL','MODES','MOGUL','MOIST','MOLDS','MOLES','MONEY','MONKS','MONTH','MOODS','MOODY','MOONS','MOORS','MOOSE','MORAL','MORPH','MOTEL','MOTHS','MOTOR','MOTTO','MOUND','MOUNT','MOURN','MOUSE','MOUTH','MOVED','MOVER','MOVES','MOVIE','MOWER','MUCUS','MUDDY','MULES','MURAL','MURKY','MUSES','MUSIC','MUTED','MYTHS','NACHO','NAILS','NAMED','NAMES','NANNY','NASAL','NASTY','NAVAL','NECKS','NEEDS','NEEDY','NERDS','NERDY','NERVE','NESTS','NEVER','NEWER','NEWLY','NEXUS','NICER','NICHE','NIECE','NIFTY','NIGHT','NINJA','NINTH','NOBLE','NODES','NOISE','NOISY','NOMAD','NORMS','NORTH','NOSED','NOSES','NOTCH','NOTED','NOTES','NOUNS','NOVEL','NUDGE','NURSE','NYLON','OASIS','OCCUR','OCEAN','ODDLY','OFFER','OFTEN','OILED','OLDER','OLIVE','OMEGA','ONION','OPENS','OPERA','OPTED','OPTIC','ORBIT','ORDER','ORGAN','OTHER','OTTER','OUGHT','OUNCE','OUTER','OVENS','OVERT','OWING','OWNED','OWNER','PACED','PACES','PACKS','PAGAN','PAGES','PAINS','PAINT','PAIRS','PALMS','PANDA','PANEL','PANIC','PANTS','PAPER','PARKS','PARRY','PARTS','PARTY','PASTA','PASTE','PATCH','PATHS','PATIO','PATTY','PAUSE','PAVED','PEACE','PEACH','PEAKS','PEARL','PEARS','PEDAL','PEERS','PENNY','PERCH','PERIL','PERKS','PESKY','PESTS','PETAL','PETTY','PHASE','PHONE','PHOTO','PIANO','PICKS','PICKY','PIECE','PIERS','PILED','PILES','PILOT','PINCH','PINES','PINTS','PIOUS','PIPER','PIPES','PITCH','PIVOT','PIXEL','PIXIE','PIZZA','PLACE','PLAID','PLAIN','PLANE','PLANK','PLANS','PLANT','PLATE','PLAYS','PLAZA','PLEAD','PLEAS','PLOTS','PLUCK','PLUGS','PLUME','PLUMP','PLUSH','POEMS','POETS','POINT','POISE','POKED','POKER','POLAR','POLES','POLLS','PONDS','POOLS','PORCH','PORES','PORTS','POSED','POSES','POSTS','POUCH','POUND','POURS','POWER','PRANK','PRAYS','PRESS','PRICE','PRIDE','PRIME','PRINT','PRIOR','PRISM','PRIZE','PROMO','PRONE','PROOF','PROPS','PROSE','PROUD','PROVE','PUBIC','PUFFS','PUFFY','PULLS','PULSE','PUMPS','PUPIL','PURGE','PURSE','QUAIL','QUAKE','QUART','QUEEN','QUERY','QUEST','QUEUE','QUICK','QUIET','QUILL','QUILT','QUIRK','QUITE','QUITS','QUOTA','QUOTE','RABID','RACED','RACER','RACES','RACKS','RADAR','RADIO','RAGED','RAGES','RAIDS','RAILS','RAINS','RAINY','RAISE','RALLY','RAMEN','RAMPS','RANCH','RANGE','RANKS','RANTS','RAPID','RATED','RATES','RATIO','RAVEN','RAZOR','REACH','REACT','READS','READY','REALM','REBEL','REEDS','REEFS','REELS','REFER','REGAL','REHAB','REIGN','REINS','RELAX','RELAY','RELIC','RENEW','RENTS','REPAY','REPEL','REPLY','RESET','RESIN','RESTS','RETRO','REUSE','REVEL','RHINO','RHYME','RIDER','RIDES','RIDGE','RIFFS','RIGHT','RIGID','RIGOR','RINGS','RINSE','RIOTS','RISEN','RISES','RISKS','RISKY','RIVAL','RIVER','ROADS','ROAST','ROBES','ROBIN','ROBOT','ROCKS','ROCKY','RODEO','ROGUE','ROLES','ROLLS','ROOFS','ROOMS','ROOTS','ROPES','ROSES','ROTOR','ROUGH','ROUND','ROUTE','ROWAN','ROWDY','ROYAL','RUGBY','RUINS','RULED','RULER','RULES','RUMOR','RURAL','RUSTY','SABER','SACKS','SADLY','SAFER','SAILS','SAINT','SALAD','SALES','SALON','SALSA','SALTS','SALTY','SANDS','SANDY','SASSY','SATIN','SAUCE','SAUNA','SAVED','SAVER','SAVES','SAVVY','SCALE','SCALP','SCAMS','SCANS','SCANT','SCARE','SCARF','SCARS','SCARY','SCENE','SCENT','SCION','SCOOP','SCOPE','SCORE','SCORN','SCOUT','SCRAP','SCRUB','SCUBA','SEALS','SEAMS','SEARS','SEATS','SEEDS','SEEKS','SEEMS','SEIZE','SELLS','SENDS','SENSE','SERGE','SERUM','SERVE','SETUP','SEVEN','SEVER','SEWER','SHACK','SHADE','SHADY','SHAKE','SHAKY','SHALL','SHAME','SHAPE','SHARE','SHARK','SHARP','SHAVE','SHAWL','SHEAR','SHEDS','SHEEN','SHEEP','SHEER','SHEET','SHELF','SHELL','SHIFT','SHINE','SHINY','SHIPS','SHIRT','SHOCK','SHOES','SHOOK','SHOPS','SHORE','SHORT','SHOTS','SHOUT','SHOVE','SHOWN','SHOWS','SHRED','SHRUB','SHRUG','SHUTS','SIDED','SIDES','SIEGE','SIGHS','SIGHT','SIGMA','SIGNS','SILKY','SILLY','SINCE','SINGS','SINKS','SINUS','SIREN','SITES','SIXTH','SIXTY','SIZED','SIZES','SKATE','SKIER','SKIES','SKILL','SKINS','SKIPS','SKIRT','SKULL','SKUNK','SLABS','SLACK','SLAMS','SLANG','SLANT','SLAPS','SLASH','SLATE','SLEEK','SLEEP','SLEPT','SLICE','SLICK','SLIDE','SLIME','SLIMY','SLING','SLIPS','SLOPE','SLOTH','SLOTS','SLOWS','SLUGS','SLUMP','SMALL','SMART','SMASH','SMEAR','SMELL','SMILE','SMIRK','SMOKE','SNACK','SNAIL','SNAKE','SNAPS','SNARE','SNEAK','SNIFF','SNOOP','SNORT','SNOUT','SNOWY','SNUCK','SOAPS','SOBER','SOCKS','SOGGY','SOILS','SOLAR','SOLID','SOLOS','SOLVE','SONAR','SONGS','SONIC','SORES','SORTS','SOULS','SOUND','SOUPS','SOUTH','SPACE','SPADE','SPANS','SPARE','SPARK','SPAWN','SPEAK','SPEAR','SPECK','SPEED','SPELL','SPELT','SPEND','SPENT','SPICE','SPICY','SPIED','SPIES','SPIKE','SPILL','SPINE','SPINS','SPIRE','SPITE','SPITS','SPLIT','SPOIL','SPOKE','SPOOF','SPOON','SPORT','SPOTS','SPOUT','SPRAY','SPREE','SPURS','SQUAD','SQUID','STABS','STACK','STAFF','STAGE','STAIN','STAIR','STAKE','STALE','STALL','STAMP','STAND','STARE','STARS','START','STASH','STATE','STATS','STAYS','STEAD','STEAK','STEAL','STEAM','STEEL','STEEP','STEER','STEMS','STEPS','STERN','STICK','STIFF','STILL','STING','STINK','STOCK','STOIC','STOKE','STOLE','STOMP','STONE','STOOD','STOOL','STOOP','STOPS','STORE','STORM','STORY','STOUT','STOVE','STRAP','STRAW','STRAY','STRIP','STRUT','STUCK','STUDY','STUFF','STUMP','STUNG','STUNT','STYLE','SUEDE','SUGAR','SUING','SUITE','SUITS','SUNNY','SUPER','SURGE','SUSHI','SWAMP','SWANS','SWAPS','SWARM','SWEAR','SWEAT','SWEEP','SWEET','SWELL','SWEPT','SWIFT','SWIMS','SWINE','SWING','SWIPE','SWIRL','SWOOP','SWORD','SWORE','SWORN','SWUNG','SYRUP','TABLE','TABOO','TACKY','TACOS','TAILS','TAKEN','TAKER','TAKES','TALES','TALKS','TALLY','TAMED','TANGO','TANKS','TAPED','TAPES','TAROT','TASKS','TASTE','TASTY','TAXED','TAXES','TAXIS','TEACH','TEAMS','TEARS','TEASE','TEENS','TEETH','TELLS','TEMPO','TEMPT','TENDS','TENOR','TENSE','TENTH','TENTS','TERMS','TESTS','TEXTS','THANK','THEFT','THEIR','THEME','THERE','THESE','THETA','THICK','THIEF','THING','THINK','THIRD','THORN','THOSE','THREE','THREW','THROW','THUGS','THUMB','THYME','TICKS','TIDAL','TIDES','TIERS','TIGER','TIGHT','TILES','TIMED','TIMER','TIMES','TIMID','TIRED','TIRES','TITAN','TITLE','TOAST','TODAY','TOKEN','TOLLS','TOMBS','TONAL','TONED','TONER','TONES','TONIC','TOOLS','TOOTH','TOPIC','TORCH','TORSO','TOTAL','TOTEM','TOUCH','TOUGH','TOURS','TOWED','TOWEL','TOWER','TOWNS','TOXIC','TOXIN','TRACE','TRACK','TRACT','TRADE','TRAIL','TRAIN','TRAIT','TRAPS','TRASH','TRAYS','TREAD','TREAT','TREES','TREND','TRIAL','TRIBE','TRICK','TRIED','TRIES','TRIPS','TROLL','TROOP','TROPE','TROUT','TROVE','TRUCE','TRUCK','TRULY','TRUNK','TRUST','TRUTH','TUBES','TUFTS','TULIP','TUMOR','TUNED','TUNES','TUNIC','TURBO','TURNS','TUTOR','TWEAK','TWEED','TWICE','TWIGS','TWINS','TWIST','TYING','TYPED','TYPES','TYPOS','ULCER','ULTRA','UNCLE','UNCUT','UNDER','UNDUE','UNFIT','UNIFY','UNION','UNITE','UNITS','UNITY','UNTIL','UPPED','UPPER','UPSET','URBAN','URGED','URGES','USAGE','USERS','USHER','USING','USUAL','UTTER','VAGUE','VALET','VALID','VALOR','VALUE','VALVE','VAPOR','VASES','VAULT','VEGAN','VEINS','VENOM','VENTS','VENUE','VERBS','VERGE','VERSE','VESTS','VIBES','VICES','VIDEO','VIEWS','VIGIL','VIGOR','VILLA','VINES','VINYL','VIOLA','VIPER','VIRAL','VIRUS','VISIT','VISTA','VITAL','VIVID','VOCAL','VOICE','VOTED','VOTER','VOTES','VOUCH','VOWED','VOWEL','WACKY','WAFER','WAGED','WAGER','WAGES','WAGON','WAIST','WAITS','WAIVE','WAKES','WALKS','WALLS','WALTZ','WANTS','WARDS','WARES','WARMS','WARNS','WARTS','WASPS','WASTE','WATCH','WATER','WAVED','WAVES','WAXED','WEARS','WEARY','WEAVE','WEDGE','WEEDS','WEEKS','WEIGH','WEIRD','WELLS','WHACK','WHALE','WHARF','WHEAT','WHEEL','WHERE','WHICH','WHIFF','WHILE','WHINE','WHIPS','WHISK','WHITE','WHOLE','WHOSE','WIDEN','WIDER','WIDOW','WIDTH','WIELD','WILLS','WINCH','WINDS','WINDY','WINES','WINGS','WIPED','WIPES','WIRED','WIRES','WISER','WITCH','WITTY','WIVES','WOMAN','WOMEN','WOODS','WORDS','WORKS','WORLD','WORMS','WORRY','WORSE','WORST','WORTH','WOULD','WOUND','WOVEN','WRAPS','WRATH','WRECK','WRIST','WRITE','WRONG','WROTE','XEROX','YACHT','YANKS','YARDS','YEARS','YEAST','YELLS','YIELD','YIKES','YOUNG','YOUTH','ZEBRA','ZEROS','ZONED','ZONES']
import type { letter } from '../scripts/letter'
export class game {
    secret: string;
    words: string[];

    constructor(){
        this.words = wordList;
        const s = Math.floor(Math.random() * (wordList.length - 1))
        this.secret = wordList[s]
    }

    validWords(g:string){
        let tempList:string[] = []
        let holdList:string[] = []
        wordList.forEach(word => {
            if(word.charAt(0) == g.charAt(0)){
              tempList.push(word)
            }
          })
          for(let j = 1; j < g.length; j++){
            if(g.charAt(j) != '?'){
                tempList.forEach(word => {
                    if(word.charAt(j) == g.charAt(j)){
                        holdList.push(word)
                    }
                })
                tempList = holdList
                holdList = []
            }
          }
          return tempList
    }

    contains(g:string){
        return wordList.includes(g)
    }

    secretContains(g:string){
        return this.secret.includes(g)
    }

    /* updateColors(rows:letter[][], g:string){
        for(let i = 0; i < 5; i++){
            if(this.secret.charAt(i) == g.charAt(i)){
                //
            }
             if(this.secret.charAt(i) == g.charAt(i)){
                if(r1.includes(g.charAt(0))){
                    rows[0].forEach(l => {
                        if(l.char == g.charAt(0)){
                            l.status = 1
                        }
                    })
                } else if (r2.includes(g.charAt(0))){
                    rows[1].forEach(l => {
                        if(l.char == g.charAt(0)){
                            l.status = 1
                        }
                    })
                } else {
                    rows[2].forEach(l => {
                        if(l.char == g.charAt(0)){
                            l.status = 1
                        }
                    })
                }
            } else if(this.secretContains(g.charAt(i))){
                if(r1.includes(g.charAt(0))){
                    rows[0].forEach(l => {
                        if(l.char == g.charAt(0)){
                            l.status = 2
                        }
                    })
                } else if (r2.includes(g.charAt(0))){
                    rows[1].forEach(l => {
                        if(l.char == g.charAt(0)){
                            l.status = 2
                        }
                    })
                } else {
                    rows[2].forEach(l => {
                        if(l.char == g.charAt(0)){
                            l.status = 2
                        }
                    })
                }
            } else {
                if(r1.includes(g.charAt(0))){
                    rows[0].forEach(l => {
                        if(l.char == g.charAt(0)){
                            l.status = 3
                        }
                    })
                } else if (r2.includes(g.charAt(0))){
                    rows[1].forEach(l => {
                        if(l.char == g.charAt(0)){
                            l.status = 3
                        }
                    })
                } else {
                    rows[2].forEach(l => {
                        if(l.char == g.charAt(0)){
                            l.status = 3
                        }
                    })
                }
            }
        } 
        return rows
    }*/
}