// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Wordle.Api.Data;

#nullable disable

namespace Wordle.Api.Migrations
{
[DbContext(typeof(AppDbContext))]
partial class AppDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "7.0.5")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity(
            "Wordle.Api.Data.Player",
            b =>
            {
                b.Property<int>("PlayerId").ValueGeneratedOnAdd().HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlayerId"));

                b.Property<double>("AverageAttempts").HasColumnType("float");

                b.Property<int>("AverageTimeInSeconds").HasColumnType("int");

                b.Property<int>("GameCount").HasColumnType("int");

                b.Property<string>("PlayerName").IsRequired().HasColumnType("nvarchar(max)");

                b.Property<double>("TotalAttempts").HasColumnType("float");

                b.Property<int>("TotalTimeInSeconds").HasColumnType("int");

                b.HasKey("PlayerId");

                b.ToTable("Players");
            });

        modelBuilder.Entity(
            "Wordle.Api.Data.Word",
            b =>
            {
                b.Property<int>("WordId").ValueGeneratedOnAdd().HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WordId"));

                b.Property<bool>("IsCommon").HasColumnType("bit");

                b.Property<bool>("IsUsed").HasColumnType("bit");

                b.Property<string>("Text").IsRequired().HasColumnType("nvarchar(max)");

                b.HasKey("WordId");

                b.ToTable("Words");
            });
#pragma warning restore 612, 618
    }
}
}
